AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ocr-indexer

Globals:
  Api:
    BinaryMediaTypes:
      - image~1gif
      - image~1png
      - image~1jpeg

Resources:

  IndexerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/ocr-indexer-1.0.jar
      Handler: ocrindexer.Indexer::handleRequest
      Runtime: java8
      MemorySize: 256
      Timeout: 60
      Role: arn:aws:iam::334165208394:role/lambda-executor
      Events:
        OcrResults:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: results/

  UploaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/ocr-indexer-1.0.jar
      Handler: ocrindexer.Uploader::handleRequest
      Runtime: java8
      MemorySize: 256
      Timeout: 60
      Role: arn:aws:iam::334165208394:role/lambda-executor
      Environment:
        Variables:
          S3_BUCKET: ocr-input.dnjo.net
          S3_PREFIX: images
      Events:
        UploadImage:
          Type: Api
          Properties:
            Path: /images
            Method: post

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "ocr-results.dnjo.net"
