AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ocr-indexer

Globals:
  Api:
    BinaryMediaTypes:
      - image~1gif
      - image~1png
      - image~1jpeg

    MethodSettings: [{
      # Turn on Info logging
      "LoggingLevel": "INFO",

      # Enable Metrics
      "MetricsEnabled": True,

      # Trace-level Logging
      "DataTraceEnabled": True,

      # On all Paths & methods
      "ResourcePath": "/*",
      "HttpMethod": "*",
    }]

Resources:

  IndexerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/ocr-indexer-1.0.jar
      Handler: net.dnjo.handler.IndexImageOcrResultHandler::handleRequest
      Runtime: java8
      MemorySize: 256
      Timeout: 60
      Role: arn:aws:iam::334165208394:role/lambda-executor
      Events:
        OcrResults:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: results/

  UploaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/ocr-indexer-1.0.jar
      Handler: net.dnjo.handler.UploadImageHandler::handleRequest
      Runtime: java8
      MemorySize: 256
      Timeout: 60
      Role: arn:aws:iam::334165208394:role/lambda-executor
      Environment:
        Variables:
          S3_BUCKET: ocr-input.dnjo.net
          S3_PREFIX: images
      Events:
        UploadImage:
          Type: Api
          Properties:
            Path: /images
            Method: post

  DeleteImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/ocr-indexer-1.0.jar
      Handler: net.dnjo.handler.DeleteImageHandler::handleRequest
      Runtime: java8
      MemorySize: 256
      Timeout: 30
      Role: arn:aws:iam::334165208394:role/lambda-executor
      Events:
        UploadImage:
          Type: Api
          Properties:
            Path: /images/{image_id}
            Method: delete

  GetImageBlobFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/ocr-indexer-1.0.jar
      Handler: net.dnjo.handler.GetImageBlobHandler::handleRequest
      Runtime: java8
      MemorySize: 256
      Timeout: 30
      Role: arn:aws:iam::334165208394:role/lambda-executor
      Events:
        UploadImage:
          Type: Api
          Properties:
            Path: /images/{image_id}/blob
            Method: get

  GetImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/ocr-indexer-1.0.jar
      Handler: net.dnjo.handler.GetImageHandler::handleRequest
      Runtime: java8
      MemorySize: 256
      Timeout: 30
      Role: arn:aws:iam::334165208394:role/lambda-executor
      Events:
        UploadImage:
          Type: Api
          Properties:
            Path: /images/{image_id}
            Method: get

  ApiGwAccountConfig:
    Type: "AWS::ApiGateway::Account"
    Properties:
      CloudWatchRoleArn: arn:aws:iam::334165208394:role/apigateway-logs

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "ocr-results.dnjo.net"
